In [1]:
import numpy as np

In [2]:
W = np.ones((5, 5)) * 0.1

In [3]:
for i in range(5):
    W[i][i] = 0.6

In [4]:
W

array([[0.6, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.6, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.6, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.6, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.6]])

In [5]:
u = np.array([6, 5, 6, 2, 1]) / 10

In [6]:
u

array([0.6, 0.5, 0.6, 0.2, 0.1])

In [17]:
M = np.array([
    -1, 0, 1, 1, 0,
    0, -1, 0, 1, 1,
    1, 0, -1, 0, 1,
    1, 1, 0, -1, 0,
    0, 1, 1, 0, -1
]) * 0.5

In [18]:
M = M.reshape((5, 5))

In [19]:
M

array([[-0.5,  0. ,  0.5,  0.5,  0. ],
       [ 0. , -0.5,  0. ,  0.5,  0.5],
       [ 0.5,  0. , -0.5,  0. ,  0.5],
       [ 0.5,  0.5,  0. , -0.5,  0. ],
       [ 0. ,  0.5,  0.5,  0. , -0.5]])

In [20]:
I = np.eye(5)
I_M = I - M

In [21]:
Wu = np.dot(W, u)

The question asked for $\textbf{v}_{ss}$, the steady-state voltage. This means that $\frac{\mathrm{d}\textbf{v}}{\mathrm{d}t}=0$. We have, 
$$\begin{aligned} \tau \frac{\mathrm{d}\textbf{v}}{\mathrm{d}t} &= -\textbf{v}+W\textbf{u}+M\textbf{v} = 0 \\ \textbf{v}_{ss} &= W\textbf{u}+M\textbf{v}_{ss} \\ I\textbf{v}_{ss} &= W\textbf{u}+M\textbf{v}_{ss} \\ (I-M)\textbf{v}_{ss} &= W\textbf{u} \\ \textbf{v}_{ss} &= (I-M)^{-1}W\textbf{u} \end{aligned}$$

In [22]:
np.dot(np.linalg.inv(I_M), Wu)

array([0.87272727, 0.79090909, 0.86363636, 0.75454545, 0.71818182])